TARGET = arcpln
OBJS = arcpln.o

INCDIR =
CFLAGS = -O2 -G0 -Wall
CXXFLAGS = $(CFLAGS) -fno-exceptions -fno-rtti
ASFLAGS = $(CFLAGS)

BUILD_PRX = 1
PRX_EXPORTS = apexp.exp

LIBDIR =
LDFLAGS = -mno-crt0 -nostartfiles
LIBS = -lpspgum -lpspgu -lm


PSPSDK=$(shell psp-config --pspsdk-path)
include $(PSPSDK)/lib/build.mak

exports:
	psp-build-exports -b apexp.exp
